table dim_Date
	lineageTag: 582b4c32-9c12-4292-9cea-06b4a7ced966

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e343cada-4c05-4586-8a21-4aba409b4306
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 9ce32699-cf33-4daf-abf1-be88233eae3a
			defaultHierarchy: LocalDateTable_cf3c17b1-ba66-47fd-968c-5c1159659b14.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ed69f62d-922a-43b0-9bd0-e073ad98d3e0
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: d49862d4-e175-4811-9d5d-7b3f215cc71b
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 56c0d248-3aaf-4545-94a2-2bd5862009d4
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 18072d6e-01fa-46c9-8e53-3ee27e53110c
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Name'
		dataType: string
		lineageTag: 81984239-52a9-488b-a76d-ae3655faae88
		summarizeBy: none
		sourceColumn: Day of Week Name

		annotation SummarizationSetBy = Automatic

	column 'Is Weekend'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: f85d537e-4d9c-4106-88b6-7baebc3c2795
		summarizeBy: none
		sourceColumn: Is Weekend

		annotation SummarizationSetBy = Automatic

	partition dim_Date = m
		mode: import
		source =
				let
				    StartDate = #date(2000, 1, 1),
				    EndDate = #date(2025, 12, 31),
				    DateList = List.Dates(
				        StartDate,
				        Duration.Days(EndDate - StartDate) + 1,
				        #duration(1, 0, 0, 0)
				    ),
				    DateTable = Table.FromList(
				        DateList,
				        Splitter.SplitByNothing(),
				        {"Date"}
				    ),
				    ChangedType = Table.TransformColumnTypes(
				        DateTable,
				        {{"Date", type date}}
				    ),
				    AddYear = Table.AddColumn(
				        ChangedType, "Year",
				        each Date.Year([Date]),
				        Int64.Type
				    ),
				    AddMonthNum = Table.AddColumn(
				        AddYear, "Month Number",
				        each Date.Month([Date]),
				        Int64.Type
				    ),
				    AddMonthName = Table.AddColumn(
				        AddMonthNum, "Month Name",
				        each Date.MonthName([Date]),
				        type text
				    ),
				    AddQuarter = Table.AddColumn(
				        AddMonthName, "Quarter",
				        each "Q" & Text.From(Date.QuarterOfYear([Date])),
				        type text
				    ),
				    AddDayName = Table.AddColumn(
				        AddQuarter, "Day of Week Name",
				        each Date.DayOfWeekName([Date]),
				        type text
				    ),
				    AddIsWeekend = Table.AddColumn(
				        AddDayName, "Is Weekend",
				        each Date.DayOfWeek([Date]) >= 5,
				        type logical
				    )
				in
				    AddIsWeekend

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

